import io
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#4b5563"))
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(A4[0] - 40, 25, page_text)
        self.drawString(40, 25, "Confidential — University Examination Paper — Generated by Agentic AI")
        self.setStrokeColor(colors.HexColor("#e5e7eb"))
        self.setLineWidth(0.5)
        self.line(40, 35, A4[0] - 40, 35)
        self.restoreState()

class QuestionPaperPDFGenerator:
    @staticmethod
    def generate_pdf(paper_data: Dict[str, Any]) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=36,
            rightMargin=36,
            topMargin=36,
            bottomMargin=45
        )

        styles = getSampleStyleSheet()
        
        # Custom Typography
        inst_title_style = ParagraphStyle(
            'InstTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=16,
            alignment=1,  # Center
            textColor=colors.HexColor("#1e293b")
        )

        sub_header_style = ParagraphStyle(
            'SubHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=13,
            alignment=1,
            textColor=colors.HexColor("#334155")
        )

        exam_name_style = ParagraphStyle(
            'ExamName',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=11,
            leading=14,
            alignment=1,
            textColor=colors.HexColor("#0f172a")
        )

        meta_label_style = ParagraphStyle(
            'MetaLabel',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1e293b")
        )

        meta_value_style = ParagraphStyle(
            'MetaValue',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#334155")
        )

        instructions_style = ParagraphStyle(
            'Instructions',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#475569")
        )

        section_heading_style = ParagraphStyle(
            'SectionHead',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10.5,
            leading=14,
            alignment=1,
            textColor=colors.HexColor("#0f172a")
        )

        q_table_head_style = ParagraphStyle(
            'QTableHead',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11,
            alignment=1,
            textColor=colors.HexColor("#0f172a")
        )

        q_num_style = ParagraphStyle(
            'QNum',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=12,
            alignment=1,
            textColor=colors.HexColor("#1e293b")
        )

        q_text_style = ParagraphStyle(
            'QText',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#0f172a")
        )

        badge_style = ParagraphStyle(
            'Badge',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            leading=10,
            alignment=1,
            textColor=colors.HexColor("#334155")
        )

        story = []

        # 1. Institutional Header
        inst_name = paper_data.get("institution_name", "Department of Computer Science & Engineering")
        story.append(Paragraph(inst_name.upper(), inst_title_style))
        story.append(Spacer(1, 2))
        
        exam_name = paper_data.get("examination_name", "Semester End Examination")
        story.append(Paragraph(exam_name, exam_name_style))
        story.append(Spacer(1, 6))

        # 2. Metadata Box Table
        course_code = paper_data.get("course_code", "CS301")
        course_name = paper_data.get("course_name") or paper_data.get("title", "Advanced Data Structures")
        duration = paper_data.get("duration_minutes", 180)
        total_marks = paper_data.get("total_marks", 70)

        meta_data = [
            [
                Paragraph(f"<b>Course Code:</b> {course_code}", meta_label_style),
                Paragraph(f"<b>Course Name:</b> {course_name}", meta_label_style)
            ],
            [
                Paragraph(f"<b>Duration:</b> {duration} Minutes", meta_value_style),
                Paragraph(f"<b>Max Marks:</b> {total_marks} Marks", meta_value_style)
            ]
        ]
        
        meta_table = Table(meta_data, colWidths=[200, 320])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 6))

        # 3. Instructions
        instructions = paper_data.get("instructions", "Answer all questions. Figures to the right indicate full marks.")
        story.append(Paragraph(f"<b>Instructions:</b> {instructions}", instructions_style))
        story.append(Spacer(1, 8))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#334155"), spaceAfter=10))

        # 4. Group questions by section
        questions = paper_data.get("questions", [])
        sections_map = {}
        for q in questions:
            sec = q.get("section_name", "Section A")
            if sec not in sections_map:
                sections_map[sec] = []
            sections_map[sec].append(q)

        for sec_name, q_list in sections_map.items():
            story.append(Paragraph(f"<b>--- {sec_name.upper()} ---</b>", section_heading_style))
            story.append(Spacer(1, 4))

            # Table Header
            table_rows = [
                [
                    Paragraph("<b>Q.No</b>", q_table_head_style),
                    Paragraph("<b>Question Description</b>", q_table_head_style),
                    Paragraph("<b>Marks</b>", q_table_head_style),
                    Paragraph("<b>CO</b>", q_table_head_style),
                    Paragraph("<b>Bloom</b>", q_table_head_style),
                ]
            ]

            for q in q_list:
                q_num = str(q.get("question_number", ""))
                q_text = q.get("question_text", "").replace("\n", "<br/>")
                marks = str(q.get("marks", ""))
                co = str(q.get("course_outcome", ""))
                bloom = str(q.get("bloom_level", ""))

                table_rows.append([
                    Paragraph(f"<b>{q_num}</b>", q_num_style),
                    Paragraph(q_text, q_text_style),
                    Paragraph(f"[{marks}]", badge_style),
                    Paragraph(co, badge_style),
                    Paragraph(bloom, badge_style),
                ])

            # Widths: Q.No: 35, QText: 345, Marks: 45, CO: 45, Bloom: 50 -> Total 520pt
            q_table = Table(table_rows, colWidths=[35, 345, 45, 45, 50])
            q_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ('BOX', (0, 0), (-1, -1), 0.8, colors.HexColor("#94a3b8")),
                ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(q_table)
            story.append(Spacer(1, 12))

        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()
